[package]
name = "timetable"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.23"
dotenv = "0.15.0"
indicatif = "0.17.2"
itertools = "0.10.5"
reqwest = { version = "0.11.13", features = ["blocking", "cookies"] }
select = "0.5.0"
tincture = "0.5.0"
